project:
  type: website
  output-dir: docs

website:
  title: "Flavia's Data Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Posts
        href: posts/

  page-navigation: true
  sidebar:
    style: floating
    contents: posts

format:
  html:
    theme: cosmo
    css: styles.css





